# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: githubio_source
    - name: Checkout SLDN
      uses: actions/checkout@v2
      with:
        repository: softlayer/softlayer.github.io
        path: softlayer.github.io
        ssh-key: ${{secrets.SLDN_SSHKEY}}
    - name: Build Hugo
      run: |
        pwd
        cd githubio_source
        ./bin/hugo -d ../softlayer.github.io -v
    - name: Publish
      run: |
        pwd
        date=`date +%s`
        cd softlayer.github.io
        git fetch --prune --unshallow
        git config --local user.email "sldndeveloperrelations@wwpdl.vnet.ibm.com"
        git config --local user.name "SLDN"
        git checkout -b ${date}
        git add --all
        git status
        git commit --message="`date` Release"
        git push origin ${date}
        git request-pull ${date} https://github.com/softlayer/softlayer.github.io master

        